// LACUNA LAZY LOAD FALLBACK
function lacuna_lazy_load(id, callback){
    fetch("http://127.0.0.1:8125/lazyload/", {
        method: "POST",
        headers: { "Accept": "application/json", "Content-Type": "application/json" },
        body: JSON.stringify({id})
    }).then(response => {
        return response.text();
    }).then(callback);
}
"undefined"==typeof window.Mozilla&&(window.Mozilla={}),function(){"use strict";var e={COOKIE_CODE_ID:"moz-stub-attribution-code",COOKIE_SIGNATURE_ID:"moz-stub-attribution-sig",withinAttributionRate:function(){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[209:254]", functionData => eval(functionData))},getAttributionRate:function(){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[284:392]", functionData => eval(functionData))},hasCookie:function(){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[413:511]", functionData => eval(functionData))},setCookie:function(t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[533:781]", functionData => eval(functionData))},getCookie:function(){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[802:933]", functionData => eval(functionData))},updateBouncerLinks:function(i){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[964:1323]", functionData => eval(functionData))},appendToDownloadURL:function(o,t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[1357:1519]", functionData => eval(functionData))},onRequestSuccess:function(t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[1548:1629]", functionData => eval(functionData))},requestAuthentication:function(t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[1663:1797]", functionData => eval(functionData))},getAttributionData:function(t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[1828:2028]", functionData => eval(functionData))},isFirefoxNewScene2:function(t){lacuna_lazy_load("lacuna_cache/imported_waxyvv.js[2059:2144]", functionData => eval(functionData))},meetsRequirements:function(){return"undefined"!=typeof window.site&&"undefined"!=typeof Mozilla.Cookies&&(!!Mozilla.Cookies.enabled()&&("windows"===window.site.platform&&!Mozilla.dntEnabled()))},init:function(){var t={};e.meetsRequirements()&&(e.hasCookie()?(t=e.getCookie(),e.updateBouncerLinks(t)):e.isFirefoxNewScene2()||(t=e.getAttributionData())&&e.withinAttributionRate()&&e.requestAuthentication(t))}};window.Mozilla.StubAttribution=e}(),function(){"use strict";Mozilla.StubAttribution.init()}();