// LACUNA LAZY LOAD FALLBACK
function lacuna_lazy_load(id, callback){
    fetch("http://127.0.0.1:8125/lazyload/", {
        method: "POST",
        headers: { "Accept": "application/json", "Content-Type": "application/json" },
        body: JSON.stringify({id})
    }).then(response => {
        return response.text();
    }).then(callback);
}
!function(e,t){lacuna_lazy_load("lacuna_cache/imported_23nkxu.js[14:291]", functionData => eval(functionData))fers=e.wafer.wafers||{},e.wafer.wafers["wafer-imlacuna_lazy_load("lacuna_cache/imported_23nkxu.js[337:5205]", functionData => eval(functionData))){___jdce_logger("lacuna_cache/imported_23nkxu.js", 3667, 3695);i(e,"srcset",n)})),this._addEventsToElement(e,a,"default",r)}}},{key:"_itemLoaded",value:function(e){___jdce_logger("lacuna_cache/imported_23nkxu.js", 3768, 3921);u(t.prototype.__proto__||Object.getPrototypeOf(t.prototype),"_itemLoaded",this).call(this,e);var r=this._options.srcset;e.removeAttribute(r)}},{key:"_addEventsToElement",value:function(e,t,r,o){___jdce_logger("lacuna_cache/imported_23nkxu.js", 3956, 4507);var n=this,a=o.elemSrc,i=o.elemSrcset,c=o.fallbackSrc,l=o.type,u=this._options,f=u.error,p=u.errorClass,d=u.src,m=u.successClass,y=function r(){___jdce_logger("lacuna_cache/imported_23nkxu.js", 4105, 4297);f&&f(e,"invalid"),e.classList.add(p),c&&(e.classList.add("wafer-img-fallback"),e.src=c),_.emitError({elem:e,meta:{src:d},name:"WaferImage",stack:{}}),g(t,"error",r),g(t,"load",b)},b=function o(){___jdce_logger("lacuna_cache/imported_23nkxu.js", 4300, 4468);"native"!==r?("image"===l||"picture"===l?s(e,a,i):e.style.backgroundImage='url("'+a+'")',n._itemLoaded(e)):e.classList.add(m),g(t,"error",y),g(t,"load",o)};v(t,"error",y),v(t,"load",b),s(t,a,i)}},{key:"_getImageMetaWithType",value:function(e){___jdce_logger("lacuna_cache/imported_23nkxu.js", 4544, 4965);var t=this._options,r=t.isRetina,o=t.separator,n=t.src,a=t.srcset,s=e.getAttribute(n),i=e.getAttribute(w+"fallback-src");if(s){var c=s.split(o),l=c[r&&c.length>1?1:0],u=e.getAttribute(a),f=e.tagName.toLowerCase(),p="img"===f,d=e.parentNode,v=d&&b(d,"picture");if(p||void 0===e.src)return v?{elemSrc:l,elemSrcset:u,fallbackSrc:i,type:"picture"}:{elemSrc:l,elemSrcset:u,fallbackSrc:i,type:p?"image":f}}return{}}}]),t}(h);O.prototype.configs={selector:".wafer-img",separator:"|",srcset:"data-wf-srcset",nativeClass:"wafer-img-native",successClass:"wafer-img-loaded",allowPrefetch:!0};var j=O;t.default=new j({selector:j.prototype.configs.selector})}})});