
        var Quizlet = {
            "LOGGED_IN": false,
            "SERVER_TIME": 1570705662,
            "DEBUG": false,
            "willHaveJquery": true,
            "willHaveMootools": false,
            "shouldReportLoggingErrors": false,
            "cstokenName": "qtkn",
            "blackAndWhitelistObfuscatedRegexesByLang": {
                "en": {
                    "black": "b\\ttubs\\ehts\\nib\\|b\\ssas\\ehts\\nib\\|huggin|eloh?]s\\-[ytoob|eloh?]s\\-[ttub|rekcuss\\)kcoc|kcid:?(|b\\?skcid?)s\\a?:(s\\?staeb\\|b\\kcids\\ymb\\|)kcoc|kcid:?(s\\)ruoy|sih|ym|a:?(s\\kcusb\\|b\\ffo?s\\gnikrejb\\|b\\ffo?]-s\\[krejb\\|b\\ffo?s\\gnikcajb\\|b\\ffo?]-s\\[kcajb\\|kcid?s\\yeknod|b\\erohwb\\|toggaf|b\\zzijb\\|b\\boj?]-s\\[wolbb\\|b\\eye?]-s\\[tnalsb\\|b\\yekcoj?]-s\\[lemacb\\|b\\ssa?]-s\\[dralb\\|b\\ssa?]-s\\[tafb\\|nmad?]-s\\[dog|daeh*s\\lewot|kcoc*s\\?skcus|kcid*s\\?skcus|regginb\\|)dr!?(agginb\\|rekcap*s\\egduf|kcuf|ssa?]-s\\[bmud|gab?]-s\\[ehcuod|b\\?stnucb\\|kcuskcoc|b\\?selohssab\\",
                    "white": "b\\tnucidb\\|ttubs\\ehts\\nis\\)mih|reh|uoy|em:?(s\\etib|ttubs\\ehts\\nis\\niap|ssas\\ehts\\nis\\niap"
                },
                "es": {
                    "black": "nole]j|g[oc|]a|o[reluc|)agrev|adreim:?(?]-s\\[al?]-s\\[a?]-s\\[etev|b\\agrevb\\|sallopalpos|b\\?sa?kkiramb\\|]o|a[damam|solucemal|atup]o|a[jih|atup?]-s\\[ed?]-s\\[]o|a[jih|ajap?]-s\\[anu?]-s\\[recah|)rod|r:?(allof|erdam]-s\\[ut]-s\\[ed]-s\\[ahcnoc|sallopapuhc|]oa[dapuhc",
                    "white": "b\\esrallofirepmeb\\|b\\arelucseb\\|b\\odapuhcs\\?ratseb\\"
                },
                "de": {
                    "black": "lethcuwhcs|rehcstulznawhcs|neppop|nrepmip|reggin|itfum|neseom|es\u00f6m|emmik|ekanak|eztarbkcak|eztof|kcifb\\|nesmub|hcsrab\\|rettirlana",
                    "white": "b\\?eztesegs\\?sehcs?'kcifb\\"
                }
            },
            "audioSpeeds": {
                "ja": {
                    "normal": 83,
                    "slow": 60,
                    "medium": 70
                },
                "ko": {
                    "normal": 83,
                    "slow": 60,
                    "medium": 70
                },
                "fr": {
                    "normal": 100,
                    "slow": 60,
                    "medium": 75
                },
                "default": {
                    "normal": 100,
                    "slow": 70,
                    "medium": 85
                }
            },
            "cloudFlareRay": "523821d8ea7dbd91-ORD",
            "didJustUpgrade": null,
            "uid": "-317141631291860234",
            "user": null,
            "ab_enrolled_variations": "",
            "abTestConfiguration": [{
                "name": "ModernizeWrite",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SetPageShowBreadcrumbs[default,growth]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SetPageTermListSignupWallEnhanced[default,growth]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "StudyPreviewAutoplay[default,growth]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "SetSearchBoostTop3[default,search]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SetSearchBoostFixFunc[default,search]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SetSearchBoostRemoveNonSignals[default,search]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "TopicPageSetCardUIV2",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "TopicPageSetCardUIV3",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SearchStudyGuideCardRedesignV2[default,marketplace]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "experiment"
            }, {
                "name": "ConfirmationScreenClearerReturn[default,subscriptions]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "SearchPageSubjectClassificationSetsResults",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "UpgradedUsersChiclet[default,subscriptions]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "PremiumContentMcqSetPageCreateFlashcardsFeature[default,marketplace]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "UpgradeScreenProductModules[default,subscriptions]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "twoColumns"
            }, {
                "name": "IAAlphaTest",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "on"
            }, {
                "name": "AllowVisitorAgePrediction",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "on"
            }, {
                "name": "DisableSignUpButtonUntilValidFormInternational",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "on"
            }, {
                "name": "DisableSignUpButtonUntilValidFormUs",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "on"
            }, {
                "name": "NewTeacherPage_07272018",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "experiment"
            }, {
                "name": "adsHoldOut_20180315",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "gqlFolders",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "fullStoryVariation",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "fullStoryVariationUk",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "webpackVariation",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "a"
            }, {
                "name": "ShowDownloadCurtainV2",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SearchShouldLogImpressions",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "SearchRedesignV1[default,marketplace]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "redesign"
            }, {
                "name": "LoginContinueWithV2[default,growth]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "SetPageHardSignup[default,growth]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "InStudyModeSignupCurtainV3[default,growth]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "experiment"
            }, {
                "name": "AssistantConfusionAlert[default,engagement]",
                "canEnroll": true,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": "control"
            }, {
                "name": "AdsLazyLoad",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "EmbeddedAdsLazyLoad",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "ShowRecommendedStudyModeBadge",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "TopLevelSubjectsMenu[default,growth]",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }, {
                "name": "ModernizeSpell",
                "canEnroll": false,
                "isEnrolled": false,
                "variationSubjectToEnrollmentRules": null
            }],
            "i18nFlagExternalizedMessages": false,
            "isPageloadDataCollectionEnabled": true,
            "adConfig": {
                "allAdsDisabled": "logged_out_homepage",
                "keyValues": {
                    "childDirected": "no",
                    "n": "en-us",
                    "l": "0",
                    "p": "1",
                    "v": "1"
                },
                "registeredAds": {
                    "WatchWallVideo": {
                        "isFlexible": false,
                        "isOutstream": true,
                        "showAdHeading": false,
                        "supportsVideo": true,
                        "useHeaderBidding": false,
                        "type": "VIDEO",
                        "autoPlayAdsMuted": false,
                        "tag": "https:\/\/pubads.g.doubleclick.net\/gampad\/ads?iu=\/6396803\/WatchWallVideo&description_url=__page-url__&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=640x360&unviewed_position_start=1"
                    }
                },
                "shouldLogAdRequests": true,
                "tagForChildDirectedTreatment": 0
            },
            "underAgeCutoff": 16,
            "upsellPrice": "\u20ac19.99",
            "upsellMonthlyPrice": "\u20ac1.67",
            "upsellProductType": 14,
            "goUpsellPrice": "\u20ac11.99",
            "goUpsellMonthlyPrice": "\u20ac1",
            "iconPaths": null,
            "recurlyKey": "ewr1-74WTM8nDUDdRhj2nlyzwZj",
            "extraSessionUUIDs": ["34ac69f0-e72b-422f-9fd7-501a1eb57d9d", "e65d9ef6-967e-4bdd-84a1-8b6e41609d7d", "3c737233-2b38-4f8f-a5c2-5d40ed6d7e17", "f45a3d56-396d-4196-8fb9-233f780cbc7a", "0f8c217e-e135-4959-a55e-4c2d2005ef36"],
            "countryCode": "nl",
            "lowerTeacherAgeBound": 20,
            "upperTeacherAgeBound": 80,
            "requestId": "zUDDJEz3GpkwaDbbdCnq",
            "colorTheme": "default",
            "upgradeData": {
                "freeTrial": {
                    "amount": 7,
                    "unit": "day"
                },
                "willUpgradeThroughPartner": false
            },
            "derivedLocale": "en-us"
        };
        Quizlet.actionString = "Homepage\"index".replace(/"/g, '/');
    