
        window.BZFD = {
            Config: {
                "cluster": "prod",
                "facebook_app_id": "862012947269736",
                "facebook_pages": "21898300328,1457722161221362,1412406255640941",
                "imageServiceUrl": "https://img.buzzfeed.com/buzzfeed-static",
                "pixiedustUrl": "https://pixiedust.buzzfeed.com",
                "isConsentRequired": true,
                "webRoot": "https://www.buzzfeed.com",
                "branchKey": "key_live_ceFzhmH1fxNfPm55351GdbnhwxioKRyh",
                "base_url": "",
                "staticRoot": "/static-assets",
                "bfAppId": 352969997,
                "bfwInfoCookie": "bf2-b_info",
                "facebookApi": {
                    "version": "v2.9",
                    "appId": "862012947269736"
                },
                "emailSignUpUrl": "https://www.buzzfeed.com/newsletter/v3/subscriptions",
                "env": "prod",
                "sentryUrl": "https://afa4961bdef04ae0ba22ae058bbf6685@sentry.io/136284",
                "canaryDeploy": false,
                "abeagle": {
                    "url": "https://abeagle-public.buzzfeed.com",
                    "isEnabled": "false"
                },
                "tracking": {
                    "pixiedust": {
                        "impression_sampling_rate": 0.05,
                        "instrumentation_sampling_rate": 0.1,
                        "performance_sampling_rate": 0.1,
                        "page_view_url": "feed"
                    },
                    "googleAnalytics": {
                        "id": "UA-1740781-1"
                    },
                    "pixels": {
                        "facebook": {
                            "custom_audience": 260954170738952
                        }
                    }
                },
                "video_app_api": "https://videoapp-api-ng.buzzfeed.com/v2/videos",
                "recsys_api_origin": "https://recsys-api.buzzfeed.com",
                "ads": {
                    "sizes": {
                        "NATIVE": [5, 5],
                        "FLUID": "fluid",
                        "RESEARCH_PIXEL": [1, 1],
                        "RESEARCH_SURVEY": [2, 2],
                        "PROGRAMMATIC_PREBID": [1, 1],
                        "PROGRAMMATIC_BILLBOARD": [970, 250],
                        "PROGRAMMATIC_HORIZONTAL_4to1": [970, 250],
                        "PROGRAMMATIC_SMARTPHONE_BANNER": [320, 50],
                        "PROGRAMMATIC_HORIZONTAL_6to1": [320, 50],
                        "PROGRAMMATIC_LEADERBOARD": [728, 90],
                        "PROGRAMMATIC_HORIZONTAL_8to1": [728, 90],
                        "PROGRAMMATIC_SUPER_LEADERBOARD": [970, 90],
                        "PROGRAMMATIC_HORIZONTAL_10to1": [970, 90],
                        "PROGRAMMATIC_VERTICAL": [300, 600],
                        "PROGRAMMATIC_VERTICAL_1to2": [300, 600],
                        "PROGRAMMATIC_MEDIUM_RECTANGLE": [300, 250],
                        "PROGRAMMATIC_TILE_1to1": [300, 250],
                        "BIGSTORY_LEGACY_PARTNER": [300, 250]
                    },
                    "programmaticSizes": [
                        [300, 250],
                        [728, 90],
                        [320, 50],
                        [300, 600],
                        [970, 250],
                        [970, 90]
                    ]
                }
            },
            Context: {
                "page": {
                    "id": 1,
                    "destination": "buzzfeed",
                    "edition": "us",
                    "localization": {
                        "country": "en-us",
                        "language": "en",
                        "locale": "en_US",
                        "translations": {
                            "ADVERTISE_WITH_BUZZFEED": "Advertise with BuzzFeed",
                            "ADVERTISE_WITH_URL": "https://advertise.buzzfeed.com",
                            "ADVERTISEMENT": "Advertisement",
                            "PAID_POST": "Paid Post",
                            "PROMOTED_BY": "Promoted By",
                            "PROMOTED": "Promoted",
                            "SPONSORED_BY": "Sponsored By",
                            "AGAIN": "Again!",
                            "AGAIN_SPAIN": "",
                            "BREAKING": "Breaking",
                            "BREAKING_NEWS": "Breaking News",
                            "BUZZFEED_HOME": "BuzzFeed Home",
                            "BUZZFEED_INC": "BuzzFeed, Inc",
                            "BUZZFEED_REPORTING_TO_YOU": "BuzzFeed, Reporting To You",
                            "BUZZFEED_QUIZZES": "BuzzFeed Quizzes",
                            "COOKIE_INFO": "Cookie Info",
                            "COPYRIGHT_BUZZFEED_INC": "Copyright BuzzFeed, Inc. All rights reserved.",
                            "CUTE": "Cute",
                            "DASHBOARD": "Dashboard",
                            "DAY_AGO": "{} day ago",
                            "DAYS_AGO": "{} days ago",
                            "EMAIL": "Email",
                            "ENTER_VALID_EMAIL": "Please enter a valid email address",
                            "FAIL": "Fail",
                            "FOLLOW_US_ON_TWITTER": "Follow us on Twitter",
                            "FOLLOW_US_ON_TWITTER_NEWS": "",
                            "FOLLOW_US_ON": "Follow us on",
                            "GET_FIRST_EMAIL": "You're almost there! Check your inbox and confirm your subscription now!",
                            "GET_OUR_AWARD_WINNING_NEWS_APP": "Get our award-winning News App!",
                            "GET_OUR_NEWS_APP": "Get our News App!",
                            "GIVE_MORE_FEEDBACK": "Give More Feedback",
                            "GO_TO_THE_RECIPE": "Go to the recipe!",
                            "GREAT": "Great!",
                            "HEY_BUZZFEED_COMMUNITY": "Hey BuzzFeed Community!",
                            "HOUR_AGO": "{} hour ago",
                            "HOURS_AGO": "{} hours ago",
                            "JUST_NOW": "just now",
                            "LATEST": "Latest",
                            "LET_US_KNOW_HOW_WE_CAN_MAKE_THE_NEW_HOMEPAGE_BETTER": "Let us know how we can make the new homepage better.",
                            "LIKE_US_ON_FACEBOOK": "Like us on Facebook",
                            "LIKE_US_ON_FACEBOOK_NEWS": "",
                            "LIKE_US_ON": "Like us on",
                            "LIVE": "LIVE",
                            "LOG_IN_OR_SIGN_UP_TO_CREATE_YOUR_OWN_POSTS": "<a href=\"/signin\" data-bfa=\"@a:vertical-more;@d:login;\">Log in</a> or <a href=\"/signup\" data-bfa=\"@a:vertical-more;@d:signup;\">sign up</a> to create your own posts.",
                            "LOG_IN_TO_BUZZFEED": "Log In To BuzzFeed",
                            "LOG_OUT": "Log Out",
                            "LOL": "LOL",
                            "MAKE_A_POST": "Make A Post!",
                            "MAKE_IT_YOUR_DEFAULT": "Make it your default.",
                            "META_DESCRIPTION_HOME": "BuzzFeed has breaking news, vital journalism, quizzes, videos, celeb news, Tasty food videos, recipes, DIY hacks, and all the trending buzz you\u2019ll want to share with your friends. Copyright BuzzFeed, Inc. All rights reserved.",
                            "META_DESCRIPTION_HOME_SPAIN": "",
                            "MINUTE_AGO": "{} minute ago",
                            "MINUTES_AGO": "{} minutes ago",
                            "MONTH_AGO": "{} month ago",
                            "MONTHS_AGO": "{} months ago",
                            "MORE_PLEASE": "More Please",
                            "MORE": "More",
                            "MY_DRAFTS": "My Drafts",
                            "NEW_POST": "New Post",
                            "NEWS": "News",
                            "NEXT_PAGE": "Next page",
                            "OMG": "OMG",
                            "PIN": "Pin",
                            "PLAY": "Play",
                            "PREVIOUS_PAGE": "Previous page",
                            "QUICKLY_CATCH_UP": "Quickly Catch Up",
                            "QUIZZES": "Quizzes",
                            "QUIZZES_ON_BUZZFEED": "Quizzes on BuzzFeed",
                            "READ_MORE": "Read More",
                            "REPORTING_TO_YOU": "Reporting To You",
                            "SEARCH": "Search",
                            "SECTIONS": "Sections",
                            "SHARE": "Share",
                            "SIGN_UP": "Sign up",
                            "SMS": "SMS",
                            "SORRY_SOMETHING_WRONG": "Sorry! Something went wrong. Please try again.",
                            "SUBSCRIBE_TO_US_ON": "Subscribe To Us On",
                            "SUBSCRIBE_TO_OUR_RSS": "Subscribe to our RSS feed",
                            "SWITCH_TO_ENGLISH": "Switch to English",
                            "SWITCH_TO_US": "Switch to US.",
                            "THANKS_FOR_YOUR_FEEDBACK": "Thanks for your feedback!",
                            "THATS_AWESOME": "That's awesome!",
                            "TOP_POSTS": "Top Posts",
                            "TOP_POSTS_THIS_WEEK": "Top Posts This Week",
                            "TRENDING_NOW": "Trending Now",
                            "TRENDING_NOW_SPAIN": "",
                            "TRENDING": "Trending",
                            "TRENDING_QUIZZES": "Trending Quizzes",
                            "TRENDING_VIDEOS": "Trending Videos",
                            "VIEW_PROFILE": "View Profile",
                            "VIEWS": "Views",
                            "WATCH": "Watch",
                            "WATCH_IT_LIVE": "Watch it live in the Facebook App",
                            "WED_LOVE_TO_HEAR_WHAT_ELSE_YOU_HAVE_TO_SAY": "We'd love to hear what else you have to say.",
                            "WED_LOVE_TO_HEAR_WHAT_ELSE_YOU_HAVE_TO_SAY_SPAIN": "",
                            "WED_LOVE_YOUR_FEEDBACK": "We'd love your feedback!",
                            "WEEK_AGO": "{} week ago",
                            "WEEKS_AGO": "{} weeks ago",
                            "WELCOME_TO_THE_NEW_BUZZFEED_HOMEPAGE": "Welcome to the new BuzzFeed homepage!",
                            "WELCOME_TO_THE_NEW_BUZZFEED_HOMEPAGE_FEEDBACK": "Welcome to the new BuzzFeed homepage!",
                            "WERE_SORRY_TO_HEAR_THAT": "We're sorry to hear that.",
                            "WERE_SORRY_TO_HEAR_THAT_SPAIN": "",
                            "WHAT_DO_YOU_THINK": "What do you think?",
                            "WIN": "Win",
                            "WTF": "WTF",
                            "YEAR_AGO": "{} year ago",
                            "YEARS_AGO": "{} years ago",
                            "YOUR_EMAIL": "Your email address"
                        }
                    },
                    "name": "home",
                    "filter": null,
                    "filters": {}
                }
            }
        };
    