// LACUNA LAZY LOAD FALLBACK
function lacuna_lazy_load(id, callback){
    fetch("http://127.0.0.1:8125/lazyload/", {
        method: "POST",
        headers: { "Accept": "application/json", "Content-Type": "application/json" },
        body: JSON.stringify({id})
    }).then(response => {
        return response.text();
    }).then(callback);
}
// An UI change targeting on 5/18/2018 will show relying party's privacy
// policy URL and terms of service URL inside the one-tap UI for new users.
// If enabled, SHOW_RP_TOS can be found in GOOGLE_ONETAP_EXPERIMENTAL_FEATURES array.
// There is another UI change that moves the two URLs into a popup confirmation
// dialog. If enabled, DISPLAY_CLICKJACKING_POPUP can be found in the experimental
// feature array.

var GOOGLE_ONETAP_EXPERIMENTAL_FEATURES = ['DISPLAY_RP_TOS'];

var PROVIDER_URL_BASE = 'https://smartlock.google.com/iframe/request';
(function(){lacuna_lazy_load("lacuna_cache/imported_a4ack0.js[562:36860]", functionData => eval(functionData))tAvailableResult",function(lacuna_lazy_load("lacuna_cache/imported_a4ack0.js[36885:48419]", functionData => eval(functionData))rted_a4ack0.js", 29347, 29628);switch(d.label){case 0:this.w(),c=new ma(this.o,this.channel),d.label=1;case 1:return d.g.push([1,3,,4]),[4,c.B(b,a)];case 2:return[2,d.a()];case 3:e=d.a();if(a.s())this.N();
else if("browserWrappingRequired"===e.type)return[2,this.D.hint(b)];throw e;case 4:return[2]}})})};a.prototype.j=function(b,a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 29647, 29989);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 29675, 29987);var c,e;return h(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 29708, 29985);switch(d.label){case 0:this.w(),c=new ia(this.o,this.channel),d.label=1;case 1:return d.g.push([1,3,,4]),[4,c.B(b,a)];case 2:return[2,d.a()];case 3:e=d.a();if(a.s())this.N();else if("browserWrappingRequired"===e.type)return[2,this.D.j(b)];throw e;case 4:return[2]}})})};a.prototype.save=function(a,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30007, 30353);return f(this,
function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30036, 30351);var b,d;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30069, 30349);switch(e.label){case 0:this.w(),b=new ja(this.o,this.channel),e.label=1;case 1:return e.g.push([1,3,,4]),[4,b.B(a,c)];case 2:return[2,e.a()];case 3:d=e.a();if(c.s())this.N();else if("browserWrappingRequired"===d.type)return[2,this.D.save(a)];throw d;case 4:return[2]}})})};a.prototype.F=function(a,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30368, 30711);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30396, 30709);var b,d;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30429, 30707);switch(e.label){case 0:this.w(),b=new sa(this.o,this.channel),e.label=1;case 1:return e.g.push([1,
3,,4]),[4,b.B(a,c)];case 2:return[2,e.a()];case 3:d=e.a();if(c.s())this.N();else if("browserWrappingRequired"===d.type)return[2,this.D.F(a)];throw d;case 4:return[2]}})})};a.prototype.A=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30726, 31045);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30752, 31043);var b,c,d,f;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 30789, 31041);switch(e.label){case 0:this.w(),b=new ka(this.o,this.channel),e.label=1;case 1:return e.g.push([1,3,,4]),c=b.B(void 0,a),d=this.D.A(),[4,Promise.all([c,d])];case 2:return e.a(),[3,4];case 3:throw f=e.a(),a.s()&&this.N(),f;case 4:return[2]}})})};
a.prototype.m=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31061, 31381);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31087, 31379);var b,c;return h(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31120, 31377);switch(d.label){case 0:this.w(),b=new T(this.o,this.channel),d.label=1;case 1:return d.g.push([1,3,,4]),[4,b.B(void 0,a)];case 2:return[2,d.a()];case 3:c=d.a();if("browserWrappingRequired"===c.type)return[2,this.D.m()];throw c;case 4:return[2]}})})};a.prototype.N=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31396, 31714);f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31414, 31712);var a,c;return h(this,function(b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31447, 31710);switch(b.label){case 0:this.w(),a=new T(this.o,this.channel),b.label=1;case 1:return b.g.push([1,
3,,4]),[4,a.B(void 0,void 0)];case 2:return[2,b.a()];case 3:c=b.a();if("browserWrappingRequired"===c.type)return[2,this.D.m()];throw c;case 4:return[2]}})})};a.prototype.dispose=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31735, 31846);if(this.U)return Promise.resolve();this.channel.dispose();this.o.dispose();return Promise.resolve()};a.prototype.w=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31861, 31900);if(this.U)throw q.Ka().h();};return a}(),m=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31915, 34691);function a(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 31926, 32021);this.za="https://provider.openyolo.org";this.ta=[];this.T=this.X=this.H=null;da()}a.c=function(a,c,d,f,g){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32025, 32509);var b=null,e=
f&&-1!==ua.indexOf(f)?f:window.parent!==window?"fullScreen":navigator.userAgent.match(ta)?"bottomSheet":"navPopout",k=P();return Promise.resolve().then(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32211, 32242);return a.race(Q(k))}).then(function(f){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32249, 32398);var l=void 0;0<d.length&&(l={feature:d});b=new ra(document,f,window.location.origin,e,c,l,g);return a.race(ha.Ja(b.b.contentWindow,k,f))}).then(function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32405, 32436);return new va(b,a)})["catch"](function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32447, 32507);null!==b&&b.dispose();a.na(c);throw q.Wa().h();})};a.prototype.pa=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32525, 32560);this.za=a;this.reset()};
a.prototype.oa=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32577, 32612);this.ta=a;this.reset()};a.prototype.qa=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32628, 32662);this.X=a;this.reset()};a.prototype.ra=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32678, 32921);if(null===a)this.T=null,this.reset();else{if("number"!==typeof a||0>a)throw Error("Invalid timeout. It must be a number greater than or equal to 0. Setting it to 0 disable timeouts.");var b=this.T!==a&&!a;this.T=a;b&&this.reset()}};a.prototype.reset=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32940, 33021);if(this.H){var a=this.H;this.H=null;a.then(function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 32994, 33018);a.dispose()})}};a.prototype.I=function(b,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33036, 33164);var d=this;this.H||
(this.H=a.c(b,this.za,this.ta,this.X,c));this.H["catch"](function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33127, 33148);d.reset()});return this.H};a.prototype.L=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33179, 33244);a=null!==this.T?this.T:a;return 0>=a?new S:new ga(a)};a.prototype.C=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33259, 33481);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33285, 33479);var b,c,d;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33320, 33477);switch(e.label){case 0:return b=this.L(3E3),c={type:"hint",options:a},[4,this.I(b,c)];case 1:return d=e.a(),[4,d.C(a,b)];case 2:return[2,e.a()]}})})};a.prototype.hint=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33499, 33725);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33525, 33723);var b,c,d;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33560, 33721);switch(e.label){case 0:return b=
{type:"hint",options:a},c=this.L(3E3),[4,this.I(c,b)];case 1:return d=e.a(),[4,d.hint(a,c)];case 2:return[2,e.a()]}})})};a.prototype.j=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33740, 33943);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33766, 33941);var b,c,d;return h(this,function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33801, 33939);switch(e.label){case 0:return b={type:"retrieve",options:a},c=this.L(3E3),[4,this.I(c,b)];case 1:return d=e.a(),[2,d.j(a,c)]}})})};a.prototype.save=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33961, 34134);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 33987, 34132);var b,c;return h(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34020, 34130);switch(d.label){case 0:return b=this.L(3E3),[4,this.I(b)];case 1:return c=
d.a(),[2,c.save(a,b)]}})})};a.prototype.A=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34149, 34315);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34174, 34313);var a,c;return h(this,function(b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34207, 34311);switch(b.label){case 0:return a=this.L(3E3),[4,this.I(a)];case 1:return c=b.a(),[2,c.A(a)]}})})};a.prototype.F=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34330, 34499);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34356, 34497);var b,c;return h(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34389, 34495);switch(d.label){case 0:return b=this.L(1E4),[4,this.I(b)];case 1:return c=d.a(),[2,c.F(a,b)]}})})};a.prototype.m=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34514, 34681);return f(this,function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34539, 34679);var a,c;return h(this,function(b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34572, 34677);switch(b.label){case 0:return a=
this.L(3E3),[4,this.I(a)];case 1:return c=b.a(),[2,c.m(a)]}})})};return a}(),p=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34696, 35193);function a(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34707, 34754);this.M=Promise.reject(q.cb().h())}a.prototype.pa=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34769, 34781);};a.prototype.oa=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34797, 34809);};a.prototype.qa=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34825, 34837);};a.prototype.ra=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34853, 34865);};a.prototype.reset=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34884, 34896);};a.prototype.C=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34911, 34936);return this.M};a.prototype.hint=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34954, 34979);return this.M};a.prototype.j=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 34994, 35019);return this.M};a.prototype.save=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 35037, 35062);return this.M};a.prototype.A=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 35077, 35102);return this.M};a.prototype.m=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 35117, 35142);return this.M};
a.prototype.F=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 35158, 35183);return this.M};return a}(),wa=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 35199, 35794);var b=a.hasOwnProperty("crypto")&&"getRandomValues"in a.crypto;b||console.warn("The current browser does not provide window.crypto.getRandomValues. This is required by the API to work. This is likely due to an old browser.");(a=a.hasOwnProperty("crypto")&&("subtle"in a.crypto||"webkitSubtle"in a.crypto))||console.warn("The current environment does not provide window.crypto.subtle. This is required by the API to work. This is likely due to an old browser, or running the API in an unsecure origin - only secure origins (https: and localhost) provide crypto.subtle.");
return b&&a}(window)?new m:new p,V=window;V.openyolo=wa;m.prototype.setProviderUrlBase=m.prototype.pa;m.prototype.setFeatureConfig=m.prototype.oa;m.prototype.setRenderMode=m.prototype.qa;m.prototype.setTimeouts=m.prototype.ra;m.prototype.hintsAvailable=m.prototype.C;m.prototype.hint=m.prototype.hint;m.prototype.retrieve=m.prototype.j;m.prototype.save=m.prototype.save;m.prototype.disableAutoSignIn=m.prototype.A;m.prototype.proxyLogin=m.prototype.F;m.prototype.cancelLastOperation=m.prototype.m;p.prototype.setProviderUrlBase=
p.prototype.pa;p.prototype.setFeatureConfig=p.prototype.oa;p.prototype.setRenderMode=p.prototype.qa;p.prototype.setTimeouts=p.prototype.ra;p.prototype.hintsAvailable=p.prototype.C;p.prototype.hint=p.prototype.hint;p.prototype.retrieve=p.prototype.j;p.prototype.save=p.prototype.save;p.prototype.disableAutoSignIn=p.prototype.A;p.prototype.proxyLogin=p.prototype.F;p.prototype.cancelLastOperation=p.prototype.m;V.OpenYoloError=y;y.prototype.type=y.prototype.type;y.prototype.message=y.prototype.message;
g.jb=q;g.gb=C;g.lb=na})(this.Ra=this.Ra||{});}).call(this);
(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 36875, 48419);'use strict';var n,p=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 36907, 36997);var b=0;return function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 36934, 36996);return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37000, 37113);var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:p(a)}},r="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,t="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37283, 37355);a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},u=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37358, 37408);u=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37371, 37383);};r.Symbol||
(r.Symbol=w)},x=function(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37411, 37494);this.m=a;t(this,"description",{configurable:!0,writable:!0,value:b})};x.prototype.toString=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37516, 37541);return this.m};
var w=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37549, 37712);function a(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37560, 37695);if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new x("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}(),z=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37717, 37950);u();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&t(Array.prototype,a,{configurable:!0,writable:!0,value:function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37903, 37932);return y(p(this))}});z=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37937, 37949);}},y=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 37953, 38034);z();a={next:a};a[r.Symbol.iterator]=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38001, 38024);return this};return a},A=function(a,
b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38037, 38101);return Object.prototype.hasOwnProperty.call(a,b)},B=function(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38104, 38304);if(b){var c=r;a=a.split(".");for(var g=0;g<a.length-1;g++){var k=a[g];k in c||(c[k]={});c=c[k]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&t(c,a,{configurable:!0,writable:!0,value:b})}};
B("WeakMap",function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38318, 39415);function b(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38330, 38344);}function c(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38344, 38418);var f=typeof e;return"object"===f&&null!==e||"function"===f}function g(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38418, 38474);if(!A(e,h)){var f=new b;t(e,h,{value:f})}}function k(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38474, 38576);var f=Object[e];f&&(Object[e]=function(l){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38518, 38574);if(l instanceof b)return l;g(l);return f(l)})}if(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38579, 38794);if(!a||!Object.seal)return!1;try{var e=Object.seal({}),f=Object.seal({}),l=new a([[e,2],[f,3]]);if(2!=l.get(e)||3!=l.get(f))return!1;l.delete(e);l.set(f,4);return!l.has(e)&&4==l.get(f)}catch(v){return!1}}())return a;var h=
"$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var m=0,d=function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 38900, 39025);this.j=(m+=Math.random()+1).toString();if(e){e=q(e);for(var f;!(f=e.next()).done;)f=f.value,this.set(f[0],f[1])}};d.prototype.set=function(e,f){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39042, 39179);if(!c(e))throw Error("Invalid WeakMap key");g(e);if(!A(e,h))throw Error("WeakMap key fail: "+e);e[h][this.j]=f;return this};d.prototype.get=function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39196, 39248);return c(e)&&A(e,h)?e[h][this.j]:void 0};d.prototype.has=function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39265, 39313);return c(e)&&A(e,h)&&A(e[h],this.j)};
d.prototype.delete=function(e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39334, 39405);return c(e)&&A(e,h)&&A(e[h],this.j)?delete e[h][this.j]:!1};return d});
B("Map",function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39426, 41543);if(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39441, 39857);if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new a(q([[d,"s"]]));if("s"!=e.get(d)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var f=e.entries(),l=f.next();if(l.done||l.value[0]!=d||"s"!=l.value[1])return!1;l=f.next();return l.done||4!=l.value[0].x||"t"!=l.value[1]||!f.next().done?!1:!0}catch(v){return!1}}())return a;z();var b=new WeakMap,c=function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 39893, 40013);this.i={};this.c=
h();this.size=0;if(d){d=q(d);for(var e;!(e=d.next()).done;)e=e.value,this.set(e[0],e[1])}};c.prototype.set=function(d,e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40030, 40250);d=0===d?0:d;var f=g(this,d);f.list||(f.list=this.i[f.id]=[]);f.a?f.a.value=e:(f.a={next:this.c,f:this.c.f,head:this.c,key:d,value:e},f.list.push(f.a),this.c.f.next=f.a,this.c.f=f.a,this.size++);return this};c.prototype.delete=function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40270, 40445);d=g(this,d);return d.a&&d.list?(d.list.splice(d.index,1),d.list.length||delete this.i[d.id],d.a.f.next=d.a.next,d.a.next.f=d.a.f,d.a.head=null,
this.size--,!0):!1};c.prototype.clear=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40464, 40517);this.i={};this.c=this.c.f=h();this.size=0};c.prototype.has=function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40534, 40566);return!!g(this,d).a};c.prototype.get=function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40583, 40626);return(d=g(this,d).a)&&d.value};c.prototype.entries=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40647, 40708);return k(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40672, 40706);return[d.key,d.value]})};c.prototype.keys=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40726, 40778);return k(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40751, 40776);return d.key})};c.prototype.values=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40798, 40852);return k(this,function(d){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40823, 40850);return d.value})};c.prototype.forEach=function(d,e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 40873, 40970);for(var f=this.entries(),l;!(l=f.next()).done;)l=
l.value,d.call(e,l[1],l[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var g=function(d,e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41026, 41305);var f=e&&typeof e;"object"==f||"function"==f?b.has(e)?f=b.get(e):(f=""+ ++m,b.set(e,f)):f="p_"+e;var l=d.i[f];if(l&&A(d.i,f))for(d=0;d<l.length;d++){var v=l[d];if(e!==e&&v.key!==v.key||e===v.key)return{id:f,list:l,index:d,a:v}}return{id:f,list:l,index:-1,a:void 0}},k=function(d,e){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41308, 41479);var f=d.c;return y(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41341, 41477);if(f){for(;f.head!=d.c;)f=f.f;for(;f.next!=f.head;)return f=f.next,{done:!1,value:e(f)};
f=null}return{done:!0,value:void 0}})},h=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41482, 41529);var d={};return d.f=d.next=d.head=d},m=0;return c});
B("Set",function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41554, 42712);if(function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 41569, 41996);if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),g=new a(q([c]));if(!g.has(c)||1!=g.size||g.add(c)!=g||1!=g.size||g.add({x:4})!=g||2!=g.size)return!1;var k=g.entries(),h=k.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=k.next();return h.done||h.value[0]==c||4!=h.value[0].x||h.value[1]!=h.value[0]?!1:k.next().done}catch(m){return!1}}())return a;z();var b=function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42018, 42129);this.b=new Map;if(c){c=
q(c);for(var g;!(g=c.next()).done;)this.add(g.value)}this.size=this.b.size};b.prototype.add=function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42146, 42220);c=0===c?0:c;this.b.set(c,c);this.size=this.b.size;return this};b.prototype.delete=function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42240, 42302);c=this.b.delete(c);this.size=this.b.size;return c};b.prototype.clear=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42321, 42359);this.b.clear();this.size=0};b.prototype.has=function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42376, 42409);return this.b.has(c)};b.prototype.entries=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42430, 42465);return this.b.entries()};b.prototype.values=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42485, 42519);return this.b.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,g){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42625, 42702);var k=this;this.b.forEach(function(h){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42665, 42700);return c.call(g,h,h,k)})};return b});
var C=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42721, 42758);return"string"==typeof a},D=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42761, 42798);return"number"==typeof a},E=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 42801, 43410);var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},F=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 43413, 43441);return null===a};function G(a,b,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 43442, 44180);a:{var g=!1;g=void 0===g?!1:g;var k=0;for(var h=!1,m=q(b),d=m.next();!d.done;d=m.next())if(d.value.optional)h=!0;else{if(h)throw Error("Argument validator encountered a required argument after an optional argument.");k++}h=b.length;if(c.length<k||h<c.length)b="Expected "+(k===h?1===k?"1 argument":k+" arguments":k+"-"+h+" arguments")+" but got "+c.length+".";else{for(k=0;k<c.length;k++)try{H(b[k],c[k],"must be ")}catch(e){g=void 0===g?!1:g;if(0>k||k>=I.length)throw Error("Argument validator received an unsupported number of arguments.");
c=I[k];b=(g?"":c+" argument ")+'"'+b[k].name+'" '+e.message+".";break a}b=null}}b&&window.console&&"function"===typeof window.console.warn&&window.console.warn(a+" failed: "+b)}function H(a,b,c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44180, 44273);c=void 0===c?"":c;if(!(a.optional&&void 0===b||a.h(b)))throw Error(c+a.g);}var I="First Second Third Fourth Fifth Sixth Seventh Eighth Ninth".split(" ");function J(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44351, 44430);return{name:a,g:"a valid string",optional:void 0===b?!1:b,h:C}}
function K(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44431, 44675);var a=[J("renderMode"),{name:"renderMode",g:"null",optional:!1,h:F}];var b=void 0===b?!1:b;return{name:"renderMode",g:a.map(function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44568, 44591);return c.g}).join(" or "),optional:b,h:function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44619, 44673);return a.some(function(g){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44645, 44671);return g.h(c)})}}}
function L(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44676, 44965);var b=a.g;0===b.indexOf("a ")?b=b.substr(2):0===b.indexOf("an ")&&(b=b.substr(3));return{name:"supportedIdTokenProviders",g:"list of "+b,optional:!1,h:function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44841, 44963);if(!c||"array"!=E(c))return!1;c=q(c);for(var g=c.next();!g.done;g=c.next())if(!a.h(g.value))return!1;return!0}}}
function M(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 44966, 45284);var b=void 0===b?!1:b;var c=new Set(a);return{name:"supportedAuthMethods",g:"list of values from ("+a.map(function(g){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45086, 45132);return g?g.toString():"undefined"}).join(", ")+")",optional:b,h:function(g){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45162, 45282);if("array"!=E(g))return!1;g=q(g);for(var k=g.next();!k.done;k=g.next())if(!c.has(k.value))return!1;return!0}}}
function N(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45285, 45873);var c=void 0===c?!1:c;var g=Object.keys(a),k=new Set(g.map(function(h){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45360, 45389);return a[h].name}));return{name:b,g:"a valid object",optional:c,h:function(h){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45438, 45871);var m;(m=!h)||(m=typeof h,m=!("object"==m&&null!=h||"function"==m));if(m)return!1;m=q(g);for(var d=m.next();!d.done;d=m.next()){d=a[d.value];var e=d.name;try{H(d,h[e])}catch(f){throw Error('must have a "'+e+'" property '+(0===f.message.indexOf("must")?"which":"as")+" "+f.message);}}h=q(Object.keys(h));for(d=h.next();!d.done;d=h.next())if(m=
d.value,!k.has(m))throw Error('must not contain a "'+m+'" property');return!0}}};var O=/^openyolo:\/\//,P=!1,Q=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 45904, 46122);this.o=a;this.s=new RegExp("^"+a);var b={uri:J("uri"),clientId:J("clientId")};this.l={u:M(["https://accounts.google.com",a+"id-and-password"]),v:L(N(b,"supportedIdTokenProviders")),context:J("context",!0)}},R=function(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46125, 46202);return b.map(function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46152, 46200);return c.replace(a.s,"openyolo://")})},S=function(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46205, 46402);a={supportedAuthMethods:R(a,b.supportedAuthMethods)};b.supportedIdTokenProviders&&(a.supportedIdTokenProviders=b.supportedIdTokenProviders);b.context&&(a.context=
b.context);return a},T=function(a,b){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46405, 46725);a={id:b.id,authMethod:b.authMethod.replace(O,a.o)};b.password&&(a.password=b.password);b.authDomain&&(a.authDomain=b.authDomain);b.displayName&&(a.displayName=b.displayName);b.profilePicture&&(a.profilePicture=b.profilePicture);b.idToken&&(a.idToken=b.idToken);b.newGrant&&(a.newGrant=b.newGrant);return a};n=Q.prototype;n.hintsAvailable=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46757, 46861);G("hintsAvailable",[N(this.l,"options")],[a]);a=S(this,a);return openyolo.hintsAvailable(a)};
n.hint=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46870, 46998);var b=this;G("hint",[N(this.l,"options")],[a]);a=S(this,a);return openyolo.hint(a).then(function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 46970, 46996);return T(b,c)})};n.retrieve=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47010, 47146);var b=this;G("retrieve",[N(this.l,"options")],[a]);a=S(this,a);return openyolo.retrieve(a).then(function(c){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47118, 47144);return T(b,c)})};n.disableAutoSignIn=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47167, 47214);return openyolo.disableAutoSignIn()};n.cancelLastOperation=function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47237, 47286);return openyolo.cancelLastOperation()};
n.setTimeouts=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47302, 47415);G("setTimeouts",[{name:"timeoutMs",g:"a valid number",optional:!1,h:D}],[a]);openyolo.setTimeouts(a)};n.setRenderMode=function(a){___jdce_logger("lacuna_cache/imported_a4ack0.js", 47432, 47499);G("setRenderMode",[K()],[a]);openyolo.setRenderMode(a)};Q.prototype.setRenderMode=Q.prototype.setRenderMode;Q.prototype.setTimeouts=Q.prototype.setTimeouts;Q.prototype.cancelLastOperation=Q.prototype.cancelLastOperation;Q.prototype.disableAutoSignIn=Q.prototype.disableAutoSignIn;Q.prototype.retrieve=Q.prototype.retrieve;Q.prototype.hint=Q.prototype.hint;
Q.prototype.hintsAvailable=Q.prototype.hintsAvailable;var U=window;U.PROVIDER_URL_BASE&&openyolo.setProviderUrlBase(U.PROVIDER_URL_BASE);U.GOOGLE_ONETAP_EXPERIMENTAL_FEATURES&&openyolo.setFeatureConfig(U.GOOGLE_ONETAP_EXPERIMENTAL_FEATURES);var V=new Q("smartlock://"),W=new Q("googleyolo://"),X=window;X.smartlock=V;X.googleyolo=W;U.smartlock=V;U.googleyolo=W;X.onSmartLockLoad&&(P=!0,X.onSmartLockLoad(V));X.onGoogleYoloLoad&&(P=!0,X.onGoogleYoloLoad(W));
document.addEventListener("DOMContentLoaded",function(){___jdce_logger("lacuna_cache/imported_a4ack0.js", 48304, 48416);P||(X.onGoogleYoloLoad&&(P=!0,X.onGoogleYoloLoad(W)),X.onSmartLockLoad&&(P=!0,X.onSmartLockLoad(V)))});}).call(this);
